# image will be published to ghcr.io/<user>/<name>
name: bnuy
# description will be included in the image's metadata
description: Based on fedora atomic, powered by carrots.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
       #- https://copr.fedorainfracloud.org/coprs/derisis13/ani-cli/repo/fedora-40/derisis13-ani-cli-fedora-%OS_VERSION%.repo
       - https://copr.fedorainfracloud.org/coprs/dyskette/trackma/repo/fedora-%OS_VERSION%/dyskette-trackma-fedora-%OS_VERSION%.repo
       #- https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-addons/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-addons-fedora-%OS_VERSION%.repo
       #- https://repo.nextdns.io/nextdns.repo
    install:
      # - micro
       - starship
       - fish
      # - kate
      # - fonts
       - git
       - fastfetch
      # - toolbx
      # - ibm-plex-sans-fonts
       - syncthing
       - trackma+qt
       - wl-clipboard
       - mozilla-openh264
       - gstreamer1-plugin-openh264
       - mesa-va-drivers-freeworld
       - ffmpeg
      # - jetbrains-mono-fonts
      # - nextdns
       - xdg-desktop-portal-kde
       - xdg-desktop-portal
      # - nheko
      # - libcap-ng-devel
      # - procps-ng-devel
      # - uksmd
       - nu
       - generic-release
       - generic-release-common
       - plasma-firewall
       - plasma-firewall-firewalld

    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
       - firefox
       - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
       - plymouth 
       - plymouth-scripts 
       - plymouth-plugin-label 
       - plymouth-theme-spinner 
       - plymouth-plugin-two-step 
       - plymouth-system-theme
       - firewall-config
       #- Fedora-release-identity-kde
       #- fedora-release
       - fedora-release-identity-kinoite
       - fedora-release-kinoite
       - fedora-release-common
       #- fedora-release-identity-basic
       #- fedora-release-identity-kde
       #- fedora-release-common
       #- fedora-logos
       - adwaita-gtk2-theme
       - noopenh264
       - highcontrast-icon-theme
       #- maliit-keyboard
       - vim-minimal
       - tmux
       - nvtop
       - openrgb-udev-rules
       - solaar-udev
       - krfb
       - krfb-libs

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
         - org.gtk.Gtk3theme.Breeze
         - org.mozilla.firefox
         #- io.gitlab.librewolf-community
         - com.valvesoftware.Steam
         - xyz.armcord.ArmCord
         - io.github.NhekoReborn.Nheko
         - io.mpv.Mpv
         - io.freetubeapp.FreeTube
         - com.github.tchx84.Flatseal
         - org.kde.gwenview
         - org.keepassxc.KeePassXC
         - org.kde.okular
         - org.onlyoffice.desktopeditors
         - org.torproject.torbrowser-launcher
      remove:
      # - org.gnome.eog
      user:
        rtracerouteepo-name: flathub

  - type: fonts
    fonts:
      nerd-fonts:
         - FiraCode
         - jetbrainsmono
      google-fonts:
         - Noto Color Emoji
         - IBM Plex Sans
         - IBM Plex Serif
         - Manrope

  - type: script
    snippets:
         - "flatpak override --user --filesystem=xdg-config/gtk-3.0:ro"
    scripts:
         - kernel.sh

  - type: chezmoi
    install_chezmoi: true
    repository: "https://codeberg.org/oomfie/carrots"
    enable_all_users: true
    run_every: '1d'
    wait_after_boot: '5m'
    disable_init: false
    disable_update: false

  - type: bling
    install:
    # - ublue-update # https://github.com/ublue-os/ublue-update
      - laptop # installs TLP and configures your system for laptop usage
    # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section
  - type: systemd
    system:
      enabled:
        - syncthing@oomfie.service # Enabled (runs on system boot)
      disabled:
        - bluetooth.service
        - flatpak-system-update.timer
    #  masked:
    #    - example.service # Masked (does not run on system boot, under any circumstances)
    #  unmasked:
    #    - example.service # Unmasked (runs on system boot, even if previously masked)
    #user:
    #  enabled:
    #    - example.timer # Enabled (runs for the user)
    #  disabled:
    #    - example.service # Disabled (does not run for the user, unless other unit strictly requires it)
    #  masked:
    #    - example.service # Masked (does not run for the user, under any circumstances)
    #  unmasked:
    #    - example.service # Unmasked (runs for the user, even if previously masked)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

