# image will be published to ghcr.io/<user>/<name>
name: bnuy
# description will be included in the image's metadata
description: a fork of ublue with personalized stuff

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
       #- https://copr.fedorainfracloud.org/coprs/dyskette/trackma/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
       - https://repo.nextdns.io/nextdns.repo
    install:
      # - micro
       - starship
       - fish
      # - kate
      # - fonts
       - git
       - fastfetch
      # - toolbx
       - ibm-plex-sans-fonts
       - syncthing
       #- trackma-qt
       - wl-clipboard
       - mozilla-openh264
       - gstreamer1-plugin-openh264
       - mesa-va-drivers-freeworld
       - ffmpeg
       - nextdns

    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
       - firefox
       - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
       - plymouth 
       - plymouth-scripts 
       - plymouth-plugin-label 
       - plymouth-theme-spinner 
       - plymouth-plugin-two-step 
       - plymouth-system-theme
       - firewall-config
       #- Fedora-release-identity-kde
       #- fedora-release
       #- f40-backgrounds
       #- fedora-logos
       - adwaita-gtk2-theme
       #- adwaita-cursor-theme
       - noopenh264

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
         - org.mozilla.firefox
         - xyz.armcord.ArmCord
         - org.wezfurlong.wezterm
         - org.keepassxc.KeePassXC
         - io.github.NhekoReborn.Nheko
         - io.mpv.Mpv
         - org.inkscape.Inkscape
         - com.valvesoftware.Steam
         - org.kde.gwenview
         - org.gtk.Gtk3theme.Breeze
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
      user:
        repo-name: flathub

  - type: fonts
    fonts:
      nerd-fonts:
         - JetBrainsMono
      google-fonts:
         - Noto Color Emoji
         - IBM Plex Sans
         - IBM Plex Serif

  - type: script
    snippets:
         - "flatpak override --user --filesystem=xdg-config/gtk-3.0:ro"
  #  scripts:
  #       - nextdns.sh

  - type: chezmoi
    install_chezmoi: true
    repository: "https://codeberg.org/oomfie/carrots"
    enable_all_users: true
    run_every: '1d'
    wait_after_boot: '5m'
    disable_init: false
    disable_update: false

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

